name: Android CI

on:
  push:
    branches:
      - main
      - orbit/main
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - orbit/main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradle wrapper cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradlewrapper

      - name: Detekt
        run: ./gradlew detekt

      - name: Lint
        run: ./gradlew lint

      - name: Markdown lint
        run: ./gradlew markdownlint

      - name: Unit tests
        run: ./gradlew test

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: test-results
          path: '**/build/reports/tests/**'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Build
        run: ./gradlew assemble

      - name: Upload tag
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew bintrayUpload
        if: startsWith(github.ref, 'refs/tags/')
