name: Android CI

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Unit tests
      run: ./gradlew test

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: test-results
        path: orbit/build/reports/tests/test

    - name: Detekt
      run: ./gradlew detekt
        
    - name: Lint
      run: ./gradlew lint
      
    - name: Build
      run: ./gradlew assemble
      
